### PR TITLE
Runtime2

### PR DESCRIPTION
**Pull request by jingxiangmo**

### CODE REVIEW

**Comment by jingxiangmo** [comment]
currently works for receiving and sending command through servos with controller

**Comment by jingxiangmo** [comment]
// TODO: clamp position to MIN and MAX
// TODO: clamp speed to MIN and MAX
// TODO: convert position to degrees (x / 4096 * 360 deg )

**Comment by hatomist** [comment]
FYI, speed is calculated as units per second. So if you want to move from one pos to another in X ms you do
abs(target_pos - current_pos)/(dt)
example - abs(2048-2100)/(20(ms)*0.001)=2600 units per sec

What time does is not described in the docs, but from the minimum of 0 and maximum of 1000 (and value step 0.1%) I guess that's just how time will scale on the servo. So 1000 will be 100% (1 servo second is 1 real second), 500 will be 50% (1 servo second is 2 real seconds) etc. 0 Should also be 100%

**Comment by jingxiangmo** [comment]
> FYI, speed is calculated as units per second. So if you want to move from one pos to another in X ms you do abs(target_pos - current_pos)/(dt) example - abs(2048-2100)/(20(ms)*0.001)=2600 units per sec
> 
> What time does is not described in the docs, but from the minimum of 0 and maximum of 1000 (and value step 0.1%) I guess that's just how time will scale on the servo. So 1000 will be 100% (1 servo second is 1 real second), 500 will be 50% (1 servo second is 2 real seconds) etc. 0 Should also be 100%

yeah that makes sense, I'll look into this thanks

**Comment by jingxiangmo** [comment]
image

Model inference loop:
- fixed building model .pt mlir
- added new models
- use runtime.rs/main.rs for inferencing model

**Review by hatomist — APPROVED** [review]
gud job

**Pull request merged**
